### ISSUE TITLE
lessen impact of Description on search?

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lighthouse.js#121]
When searching for something like https://lighthouse.lbry.io/search?s=open-source-video-editing-lesson-4&size=50&from=0, lbry://one comes up first because it was `video` in the description. 

Can we lessen the impact of description search or make it only return if there is more than a single word match?

**Comment by kauffj** [comment]
I'm fine with tweaking this, but I really think #106 is the key here.

**Comment by tiger5226** [comment]
We need to investigate if we can set a minimum match quantity for the match query of elastic search.

**Comment by tiger5226** [comment]
this is now resolved. It wasn't description weight.
