### ISSUE TITLE
Support new metadata / types

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lighthouse.js#151]
Support new metadata added in types:
https://github.com/lbryio/types/blob/a6f2fd6d5f382f0012383b9076d650c1f6791ada/v2/proto/claim.proto#L29

Also, NSFW/Mature field is changing to a tag

**Comment by tiger5226** [comment]
This should happen automatically once Chainquery is able to parse the latest version of the proto files. Once this is live we can just test that it shows in the search result's value.

**Comment by tiger5226** [comment]
Done
