### ISSUE TITLE
Parameter to block mature content / list of tags

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lighthouse.js#166]
Today on the app side we block mature content after it's returned from Lighthouse. Instead, we'd want to be able to pass a list of tags that we want to exclude from results. 

We should also be able to pass a list of tags to include in results as well.

**Comment by kauffj** [comment]
@tzarebczan fyi @tiger5226 is about to go hog wild on elastic so if you've got ideas now is the time to bring them :stuck_out_tongue:

**Comment by tiger5226** [comment]
There is now a search parameter for nswf that takes true/false and filters. If you dont care dont pass it.
