### ISSUE TITLE
partial search matches for channels (with @ in front) don't return properly

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lighthouse.js#167]
If you remove the @, `thecrazygamer` returns the channel correctly. I don't think the desktop app should be responsible for stripping this off.  `@thecrazygamer16` also returns correctly.

**Comment by tiger5226** [comment]
It's in the results just not the top 1000 when searched that way. It is a weight issue it appears. I can resolve it by setting a high weight for a prefix check without the `@`. However, it could impact other results too. I created a PR with this change.

**Comment by tiger5226** [comment]
fixed
