### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by btzr-io** [lbryio/lighthouse.js#49]
### Filtering server side
Is there any news / plans for filter integration, 
like search only for a specific `content type`: audio / video / files, 
or `channel` and `tags`...
(if the daemon ever support it) :upside_down_face: 

https://github.com/lbryio/lbry-app/issues/664#issuecomment-335684392

**Comment by filipnyquist** [comment]
Yes, we have this metadata in the search database, when chainquery is added this will be possible to do!

**Comment by tiger5226** [comment]
We can extend the search api so it resembles a more common example. Right now we only accept 1 parameter which is the search string. 

We should have a set of arguments that are defined for advanced search capabilities. For example:

1) Channel or Claim or Playlist, etc
2) ClaimID ( there are some less known ways defined for the protocol  )
3) Active in claim trie
4) language
5) content type
6) By Publisher
7) controlling claims

Probably a lot more ways to search but we should be able to have a better api for this. Would love some feedback on an advanced search capability. Knowing what we need or expect will help in designing the best format for the api.

**Comment by kauffj** [comment]
@tiger5226 I'm for providing this functionality, but the vast majority of users are going to be used to a single box where they type things and get what they want. I think it's important we prioritize this use-case over advanced searching which is more likely to be for power users.

**Comment by lyoshenka** [comment]
agreed, not a priority right now

**Comment by tiger5226** [comment]
Ok all clear!

So then keeping the same search field for lighthouse we could enhance the field to allow for tags. This also allows the feature to be there before it is released in the app. 

so if a user types `contentType:` followed by a word (or phrase in quotes ) it will create a tag in the app. that appears like `contentType: files`. This lets the user know they are searching only files with that tag. Below is an example of  tag system is OSX search.
<img width="244" alt="screen shot 2018-03-17 at 12 01 49 pm" src="https://user-images.githubusercontent.com/3402064/37557440-1afa7216-29db-11e8-9ab8-596421d4b21f.png">

Our tags based on current information in the elastic document are as follows: 
`controllingClaims: <boolean>`
`channels: <boolean>`
`Author: "<phrase>"`
`Language: <isocode>`
`ActiveClaim: <boolean>`
`contentType: <type>`

Below is and example elastic document stored in elastic search:
```
{
  "name": "pok-mon-from-other-games-gabby-games",
  "claimId": "da73dabbc78e429254fec760d1dc97cc179b7878",
  "value": {
    "claimType": "streamType",
    "stream": {
      "metadata": {
        "preview": "",
        "license": "Copyrighted (contact author)",
        "licenseUrl": "",
        "thumbnail": "http:\/\/berk.ninja\/thumbnails\/nz7uDRZBKCo",
        "nsfw": false,
        "author": "Rerez",
        "description": "Nintendo needs new Pok\u00e9mon! Gabby is here to help!\nSubscribe to Rerez: https:\/\/goo.gl\/0qauGx\nBecome a Patron!: https:\/\/www.patreon.com\/rerez\nFollow Rerez on Twitter: https:\/\/twitter.com\/RerezTV\n\nCheck out Adam's work at: https:\/\/www.youtube.com\/user\/ItsaDogandGame\n\nRerez is a YouTube channel presented by Shane Luis all about video games. Presenting you the newest, strangest and most unique gaming topics. Featuring high quality reviews of new video games, consoles, previews, oddities, rare titles, unknown hardware, classic and retro games, and much more!\n\nCredits:\n...\nhttps:\/\/www.youtube.com\/watch?v=nz7uDRZBKCo",
        "language": "en",
        "title": "Pok\u00e9mon From Other Games! - Gabby Games - Rerez",
        "version": "_0_1_0"
      },
      "source": {
        "sourceType": "lbry_sd_hash",
        "source": "e427b1add5f93adcc21a6623c8664319cd9f2353bcf5499b32ca2d204c623d9f7014cf8c679bdb573c988e8e7a4bd983",
        "version": "_0_0_1",
        "contentType": "video\/mp4"
      },
      "version": "_0_0_1"
    },
    "publisherSignature": {
      "signature": "07c1825acf0a764a38ec92dc1c348d36eb9efc3126c821d452a80e0c75a13200923c7d8d91485e750e55577c826b8c22a5ef83ed136296ad2bcd039fd2b7af34",
      "certificateId": "6f36dfa66117b39500d6a74da38ddcb5a37301d8",
      "signatureType": "SECP256k1",
      "version": "_0_0_1"
    },
    "version": "_0_0_1"
  }
}
```

So what we do here is check if the first term in a search query is a keyword for a tag. If so we process it as such. If the next two characters is ` "` then we split the string to get phrases associated with the tag. The rest is the search query. 

We can start off allowing 1 tag, then can extend to allow for n tags. 

This should keep it independent of the apps features and allows it to be used straight away.

**Comment by btzr-io** [comment]
Would be possible to add read / add tags inside description?
My proposal would be to add the tags in the last line of the claim description:
```
This is a video a about cats!
Please support my chanel: <http://click.bait.com>
Tags: cat, funny, awesome  // <- HERE
```
Then we just need to read the last line:
```
ParseTags(description) -> [cat, funny, awesome]
```

We can also add a simple form to attach this last line for better (UX) inside the publish page:
![image](https://user-images.githubusercontent.com/14793624/37877913-42fdac42-3016-11e8-92ab-471da29eaacd.png)

**Comment by kauffj** [comment]
@tiger5226 or @filipnyquist is this viable to pursue now that chainquery is integrated?

**Comment by kauffj** [comment]
The most immediately useful filter would be filtering by file type.

**Comment by kauffj** [comment]
A lot of @jamesbiller proposed maker community initiatives could really use the ability to filter by file types.

I split out this aspect of filtering into a separate ticket: #111

**Comment by tiger5226** [comment]
>@tiger5226 or @filipnyquist is this viable to pursue now that chainquery is integrated?

I believe I missed this comment, but I don't think Chainquery is required here. This has been ready for a while, but it was put on the backburner a while ago because it was not urgent and seen as a power user feature. I like the idea to split out the file type stuff.

**Comment by tiger5226** [comment]
done
